New data versions
Sage-Bionetworks/magora pull request #23
Opened 2020-11-10 19:23 UTC by sharlagelfand

Using new versions of data - updated 5XFAD TPM counts, and app/ps1 data and metadata. Not much change to the code (except handling specimen ID instead of individual ID), but updates to the raw data (not checked in here) and the app data.

2020-11-10 19:42 UTC, karawoo requested changes
Thanks for this update! I think we should track the versions of files we're getting (see inline comments), otherwise this looks good to me.

2020-11-10 19:42 UTC, karawoo commented on data-raw/gene_expressions.R
> +# synGet("syn22103212", downloadLocation = here::here("data-raw", "gene_expressions", "5xfad"))
`synGet()` has a `version` argument -- since these files have already changed once, can we track which version you're using here?

2020-11-10 19:42 UTC, karawoo commented on data-raw/gene_expressions.R
> +# synGet("syn22103213", downloadLocation = here::here("data-raw", "gene_expressions", "5xfad"))
Can we add the version here as well?

2020-11-10 21:19 UTC, sharlagelfand commented
Thanks - have explicitly tracked and queried all the versions used now!

2020-11-11 18:54 UTC, karawoo approved these changes
LGTM, I guess the failures are the same weird vdiffr issue as with the other PR. I think they're unrelated so will merge.

2020-11-11 18:55 UTC, merged